"""add wechat params column to user table

Revision ID: 42d58e839941
Revises: f080014286b1
Create Date: 2025-10-22 10:03:58.215605

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42d58e839941'
down_revision = 'f080014286b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wechat_openid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('user', sa.Column('wechat_nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('wechat_avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_user_wechat_openid'), 'user', ['wechat_openid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wechat_openid'), table_name='user')
    op.drop_column('user', 'wechat_avatar_url')
    op.drop_column('user', 'wechat_nickname')
    op.drop_column('user', 'wechat_openid')
    # ### end Alembic commands ###
