"""modify item table

Revision ID: e250c54ab42d
Revises: 42d58e839941
Create Date: 2025-10-27 18:36:23.239197

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e250c54ab42d'
down_revision = '42d58e839941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.add_column('item', sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_item_deleted_at'), 'item', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'item', 'user', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_deleted_at'), table_name='item')
    op.drop_column('item', 'delete_reason')
    op.drop_column('item', 'deleted_by')
    op.drop_column('item', 'deleted_at')
    # ### end Alembic commands ###
