"""add last_login columns to user table

Revision ID: f080014286b1
Revises: a9660ec64a79
Create Date: 2025-10-21 11:23:24.793409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f080014286b1'
down_revision = 'a9660ec64a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_time')
    # ### end Alembic commands ###
